views:
  # Overview View - Most common metrics for dashboards
  - name: sales_overview
    title: Sales Overview
    description: Common sales metrics with standard dimensions for dashboards and quick analysis

    cubes:
      - join_path: transaction_lines
        includes:
          # Core revenue metrics
          - total_revenue
          - net_revenue
          - units_sold
          - units_returned
          - total_tax
          # Calculated metrics
          - average_order_value
          - average_selling_price
          - transaction_count
          - sku_count

      - join_path: transaction_lines.transactions
        includes:
          # Time dimensions
          - trandate
          - year
          - quarter
          - month
          # Transaction attributes
          - type
          - status

      - join_path: transaction_lines.locations
        includes:
          - name
          - channel_type
          - region

      - join_path: transaction_lines.items
        includes:
          - itemid
          - displayname
          - itemtype
          - category
          - season
          - size
          - range

  # Inventory Snapshot View - Current stock positions
  - name: inventory_snapshot
    title: Inventory Snapshot
    description: Current inventory levels with product and location details

    cubes:
      - join_path: inventory
        includes:
          # Stock measures
          - total_stock
          - available_stock
          - backorder_units
          - position_count
          - sku_count
          - location_count
          - zero_stock_positions
          - negative_stock_positions
          # Dimensions
          - stock_status

      - join_path: inventory.locations
        includes:
          - name
          - channel_type
          - region
          - location_type

      - join_path: inventory.items
        includes:
          - name: itemid
            alias: sku
          - name: displayname
            alias: product_name
          - itemtype
          - category
          - season

  # Customer Insights View - B2C customer analysis
  - name: customer_insights
    title: Customer Insights
    description: B2C customer metrics for retention and LTV analysis

    cubes:
      - join_path: b2c_customers
        includes:
          # Measures
          - customer_count
          - total_lifetime_value
          - average_ltv
          - total_orders
          - repeat_customers
          - repeat_rate
          # Dimensions
          - email
          - billing_country
          - first_order_date
          - last_order_date
          - order_count
          - lifetime_value
          - customer_tier
          - recency_bucket

  # Inventory Adjustments View - Shrinkage and correction tracking
  - name: adjustment_overview
    title: Inventory Adjustments
    description: Inventory adjustment metrics for shrinkage, corrections, and write-downs

    cubes:
      - join_path: inventory_adjustments
        includes:
          - adjustment_value
          - adjustment_count
          - shrinkage_value
          - shrinkage_units
          - positive_adjustment_value
          - positive_adjustment_units
          - item_count
          - transaction_date
          - adjustment_type
          - location_name
          - subsidiary

  # Vendor Spend View - AP and supplier analysis
  - name: vendor_spend_overview
    title: Vendor Spend
    description: Vendor bill analysis for supplier concentration and spend tracking

    cubes:
      - join_path: vendor_spend
        includes:
          - total_spend
          - bill_count
          - vendor_count
          - bill_date
          - vendor_name
          - currency_name
          - subsidiary

  # Journal Entries View - D&A and controls monitoring
  - name: journal_entries_overview
    title: Journal Entries
    description: Journal entry monitoring and D&A extraction for EBITDA

    cubes:
      - join_path: journal_entries
        includes:
          - depreciation_amortization
          - journal_entry_count
          - journal_line_count
          - total_debits
          - total_credits
          - journal_date
          - accttype
          - subsidiary

  # Customer Deposits View - Cash received before fulfillment
  - name: customer_deposits_overview
    title: Customer Deposits
    description: Customer deposit inflows and payment method mix

    cubes:
      - join_path: customer_deposits
        includes:
          - deposit_inflow
          - deposit_count
          - deposit_transaction_count
          - deposit_date
          - paymentmethod
          - customer_type
          - subsidiary

  # Deposit Applications View - Deferred revenue timing
  - name: deposit_applications_overview
    title: Deposit Applications
    description: Applied deposits and application timing

    cubes:
      - join_path: deposit_applications
        includes:
          - applied_value
          - application_count
          - application_transaction_count
          - application_date
          - deposit_date
          - customer_type
          - subsidiary

  # Customer Payments View - Cash collections
  - name: customer_payments_overview
    title: Customer Payments
    description: Customer payment collections and method mix

    cubes:
      - join_path: customer_payments
        includes:
          - cash_collected
          - payment_count
          - payment_transaction_count
          - payment_date
          - paymentmethod
          - customer_type
          - subsidiary
